# Site settings
title: Is Shell Command ______ Portable?
email: mail@michael.kropat.name
description: > # this means to ignore newlines until "baseurl:"
  A survey of what shell commands are available from /bin/sh on different platforms.
baseurl: "/is-shell-portable" # the subpath of your site, e.g. /blog/
url: "http://www.codetinkerer.com" # the base hostname & protocol for your site
twitter_username: MichaelKropat
github_username:  mkropat

# Build settings
markdown: kramdown
