#!/bin/sh

script="$1"
shift

if [ -z "$script" ]; then
    echo "Must specify a script to run" >&2
    exit 1
fi

while read -r box rest; do
    boxes="$boxes $box"
done < boxes.txt

mkdir -p "$script-results"


for box in $boxes; do
    echo "### $box ###"

    if [ ! -f ".$box.config" ]; then
        vagrant ssh-config "$box" >| ".$box.config"
    fi

    scp -F ".$box.config" "$script" "$box":
    if [ -n "$@" ]; then
        scp -F ".$box.config" "$@" "$box":
    fi

    ssh -F ."$box".config "$box" /bin/sh "$script" >| "$script-results/$box.log"
done
