#!/bin/sh

results_dir="$1"
shift

script="$1"
shift

if [ -z "$script" ]; then
    echo "Must specify a script to run" >&2
    exit 1
fi

jq -r "keys[]" < boxes.json > boxes.txt
while read -r box rest; do
    boxes="$boxes $box"
done < boxes.txt
rm -f -- boxes.txt

mkdir -p "$results_dir"

for box in $boxes; do
    echo "### $box ###"

    if [ ! -f ".$box.config" ]; then
        vagrant ssh-config "$box" >| ".$box.config"
    fi

    scp -F ".$box.config" "$script" "$box":
    if [ -n "$@" ]; then
        scp -F ".$box.config" "$@" "$box":
    fi

    ssh -F ."$box".config "$box" /bin/sh "$script" >| "$results_dir/$box.csv"
done
